### ISSUE TITLE
404 not found: ksmbd

### ISSUE THREAD

**Issue by Neustradamus** [immortalwrt/packages#102]
Bad reading, it is https://github.com/immortalwrt/packages/tree/master/kernel/ksmbd.

**Comment by 1715173329** [comment]
immortalwrt/immortalwrt#461

**Comment by ElonH** [comment]
@1715173329 how about block this user @Neustradamus

**Comment by 1715173329** [comment]
> @1715173329 how about block this user @Neustradamus

It makes sense.
