### ISSUE TITLE
luci-app-zerotier	git-24.011.13033-d800e19

### ISSUE THREAD

**Issue by naoki66** [immortalwrt/packages#1088]
多台电脑一直用ZeroTier组网，速度还行。但是不知道从哪个版本开始，打开自动客户端 NAT后，能访问网段内的设备，却无法访问网关。
例如IP地址为192.168.5.1的ImmortalWrt 配置好了后，可以从别的地方访问192.168.5.7的NAS，但是访问192.168.5.1提示192.168.5.1 已拒绝连接。
防火墙配置没有看到有关于ZeroTier的配置，uhttpd监听配置也未修改。
![image](https://github.com/immortalwrt/packages/assets/22931306/16092918-6040-4a87-aaac-a2e7c03578f8)

具体测试版本：ImmortalWrt 23.05-SNAPSHOT r27506-c520ea6730 / LuCI openwrt-23.05 branch git-24.047.26465-3c1336f

期待大佬给与提示用以修复这个问题。

**Comment by douglarek** [comment]
You can follow the instructions in this post (https://www.right.com.cn/forum/thread-8173579-1-1.html) to operate. Do not directly modify the firewall configuration here, as you may not handle it properly.

按这个帖子（ https://www.right.com.cn/forum/thread-8173579-1-1.html ）操作即可，不要直接动这里的防火墙配置，你可能把握不住。

**Comment by 1715173329** [comment]
默认不允许访问设备本身，如有需要自行更改防火墙设定。
