### ISSUE TITLE
求教大佬，Makefile中PKG_MIRROR_HASH是如何计算出来的？

### ISSUE THREAD

**Issue by qwerttvv** [immortalwrt/packages#1102]
比如已知

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://www.github.com/pymumu/smartdns.git
PKG_SOURCE_VERSION:=04d68e7797d32c02b76b51aa7556cc9e73b7892d

那么PKG_MIRROR_HASH:=什么？咋计算出来啊？

必须有这个值，不能用PKG_MIRROR_HASH:=skip，不然后续会报错退出

我尝试了这样计算smartdns.tar.xz的sha256，不对
git checkout 04d68e7797d32c02b76b51aa7556cc9e73b7892d
git archive --format=tar HEAD | xz > smartdns.tar.xz

**Comment by xlighting2017** [comment]
https://openwrt.org/docs/guide-developer/packages#use_source_repository

**Comment by qwerttvv** [comment]
> https://openwrt.org/docs/guide-developer/packages#use_source_repository

多谢，我就是搜到这个才尝试git archive --format=tar HEAD | xz > smartdns.tar.xz然后计算sha265填写到makefile的，但是到编译时候就报错说Package HASH check failed

**Comment by umlka** [comment]
PKG_MIRROR_HASH:=skip然后make package/net/smartdns/check V=s FIXUP=1

**Comment by qwerttvv** [comment]
> PKG_MIRROR_HASH:=skip然后make package/net/smartdns/check V=s FIXUP=1

多谢多谢，我知道这个，我是用https://github.com/openwrt/gh-action-sdk ，所以没办法FIXUP=1，我再琢磨琢磨

**Comment by science2468** [comment]
你把软件包源码下载下来用7-zip查看下然后填进去试试看。我记得是校验和。

**Comment by xlighting2017** [comment]
这个字段，你确定是必须要有的么？

**Comment by qwerttvv** [comment]
我用的是https://github.com/openwrt/gh-action-sdk，不填写这个就不行，似乎是openwrt/gh-action-sdk一个陈年bug了

这个是sha256，不折腾了，等openwrt/gh-action-sdk修吧，回头skip能用就行了，实在不行不用openwrt/gh-action-sdk了，手搓
