### ISSUE TITLE
shadowsocks-libev库中的ss-rules请求对nftset添加timeout flag。代码已给出。

### ISSUE THREAD

**Issue by hyfink** [immortalwrt/packages#1118]
文件位置：net/shadowsocks-libev/files/ss-rules/set.uc
104 行。
flags interval; 改为flags interval,timeout;

添加这个参数，主要是为了配合一些dns分流（动态添加ip到ss-redir的nftset规则里），以便加入nftset的ip数量在一个可控范围内，优化一点性能。
这个并不影响ss-rules自带的添加规则。

@yousong 我查看ss-libev的提交记录，最后一个是你，方便的话考虑一下。谢谢。

**Comment by 1715173329** [comment]
该软件包已被弃用，将于最近移除。
