### ISSUE TITLE
WARNING: Makefile

### ISSUE THREAD

**Issue by yxjdssai01** [immortalwrt/packages#1190]
### Describe the bug

╰─λ ./scripts/feeds install -a
Collecting package info: done
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
Installing all packages from feed packages.
WARNING: Not overriding core package 'open-app-filter'; use -f to force
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed kenzo.
Installing all packages from feed small.

### ImmortalWrt version

snapshot

### ImmortalWrt release

snapshot

### ImmortalWrt target/subtarget

MT7261

### Device

Newifi-D2

### Image kind

Official downloaded image

### Steps to reproduce

╰─λ ./scripts/feeds install -a
Collecting package info: done
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-passwall/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/small/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/shadowsocksr-libev/Makefile' has a dependency on 'libpcre', which does not exist
Installing all packages from feed packages.
WARNING: Not overriding core package 'open-app-filter'; use -f to force
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed kenzo.
Installing all packages from feed small.

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by yyshell** [comment]
run"rm -fr bin/ dl/ staging_dir/ build_dir/ tmp/ " and update again.
this will resovle most of the issue above. but I still got telephony lack "libpcre" warning.

**Comment by lovestudygithub** [comment]
环境的安装建议你用官方的方法2，接下来安装下面的办法
git clone https://github.com/immortalwrt/immortalwrt
    cd immortalwrt
    git tag
    git branch
    git checkout v23.05.2  #在tag里有版本号，填入你要的版本号，我选我现在最新的v23.05.2
    ./scripts/feeds update -a
    ./scripts/feeds install -a
    make menuconfig
    make download -j8
    make V=s -j1

这样就不会有 'libpcre', which does not exist. 这个错误提示了。

此办法来自于：https://forum.openwrt.org/t/debian-10-build-environment-missing-libraries/81977/15

**Comment by LeeHe-gif** [comment]
把makefile里的libpcre改成libpcre2就可以了，前提是你真的配置好了环境。

**Comment by 1715173329** [comment]
libpcre 已经被移除，freeswitch 目前基本上没人用可以忽略。至于引入第三方 feeds 缺依赖，自行负责。
