### ISSUE TITLE
最近ruby编译不了

### ISSUE THREAD

**Issue by luojixinhao** [immortalwrt/packages#1251]
### Describe the bug

ERROR: package/feeds/packages/ruby [host] failed to build.

### ImmortalWrt version

r30892-e58cbf60fa 

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

ramips/mt7621

### Device

Xiaomi Mi Router 3 Pro

### Image kind

Self-built image

### Actual behaviour

貌似ruby升级版本后就编译不成功了，只能把需要他的包都去掉才行。

### Diffconfig

```text
CONFIG_PACKAGE_netdata=y
CONFIG_PACKAGE_luci-app-netdata=y
CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y

#
# Ruby
#
CONFIG_PACKAGE_ruby=y

#
# Standard Library
#
# CONFIG_PACKAGE_ruby-stdlib is not set
# CONFIG_PACKAGE_ruby-abbrev is not set
# CONFIG_PACKAGE_ruby-base64 is not set
# CONFIG_PACKAGE_ruby-benchmark is not set
CONFIG_PACKAGE_ruby-bigdecimal=y
# CONFIG_PACKAGE_ruby-bundler is not set
# CONFIG_PACKAGE_ruby-cgi is not set
# CONFIG_PACKAGE_ruby-continuation is not set
# CONFIG_PACKAGE_ruby-coverage is not set
# CONFIG_PACKAGE_ruby-csv is not set
CONFIG_PACKAGE_ruby-date=y
# CONFIG_PACKAGE_ruby-debug is not set
# CONFIG_PACKAGE_ruby-delegate is not set
# CONFIG_PACKAGE_ruby-dev is not set
# CONFIG_PACKAGE_ruby-did-you-mean is not set
CONFIG_PACKAGE_ruby-digest=y
# CONFIG_RUBY_DIGEST_USE_OPENSSL is not set
# CONFIG_PACKAGE_ruby-drb is not set
CONFIG_PACKAGE_ruby-enc=y
# CONFIG_PACKAGE_ruby-enc-extra is not set
# CONFIG_PACKAGE_ruby-english is not set
# CONFIG_PACKAGE_ruby-erb is not set
# CONFIG_PACKAGE_ruby-error_highlight is not set
# CONFIG_PACKAGE_ruby-etc is not set
# CONFIG_PACKAGE_ruby-expect is not set
# CONFIG_PACKAGE_ruby-fcntl is not set
# CONFIG_PACKAGE_ruby-fiddle is not set
# CONFIG_PACKAGE_ruby-fileutils is not set
# CONFIG_PACKAGE_ruby-find is not set
# CONFIG_PACKAGE_ruby-forwardable is not set
# CONFIG_PACKAGE_ruby-gems is not set
# CONFIG_PACKAGE_ruby-getoptlong is not set
# CONFIG_PACKAGE_ruby-io-console is not set
# CONFIG_PACKAGE_ruby-io-nonblock is not set
# CONFIG_PACKAGE_ruby-io-wait is not set
# CONFIG_PACKAGE_ruby-ipaddr is not set
# CONFIG_PACKAGE_ruby-irb is not set
# CONFIG_PACKAGE_ruby-json is not set
# CONFIG_PACKAGE_ruby-logger is not set
# CONFIG_PACKAGE_ruby-matrix is not set
# CONFIG_PACKAGE_ruby-minitest is not set
# CONFIG_PACKAGE_ruby-mjit is not set
# CONFIG_PACKAGE_ruby-mkmf is not set
# CONFIG_PACKAGE_ruby-monitor is not set
# CONFIG_PACKAGE_ruby-mutex_m is not set
# CONFIG_PACKAGE_ruby-net-ftp is not set
# CONFIG_PACKAGE_ruby-net-http is not set
# CONFIG_PACKAGE_ruby-net-imap is not set
# CONFIG_PACKAGE_ruby-net-pop is not set
# CONFIG_PACKAGE_ruby-net-protocol is not set
# CONFIG_PACKAGE_ruby-net-smtp is not set
# CONFIG_PACKAGE_ruby-nkf is not set
# CONFIG_PACKAGE_ruby-objspace is not set
# CONFIG_PACKAGE_ruby-observer is not set
# CONFIG_PACKAGE_ruby-open-uri is not set
# CONFIG_PACKAGE_ruby-open3 is not set
# CONFIG_PACKAGE_ruby-openssl is not set
# CONFIG_PACKAGE_ruby-optparse is not set
# CONFIG_PACKAGE_ruby-ostruct is not set
# CONFIG_PACKAGE_ruby-pathname is not set
# CONFIG_PACKAGE_ruby-powerassert is not set
# CONFIG_PACKAGE_ruby-pp is not set
# CONFIG_PACKAGE_ruby-prettyprint is not set
# CONFIG_PACKAGE_ruby-prime is not set
# CONFIG_PACKAGE_ruby-prism is not set
CONFIG_PACKAGE_ruby-pstore=y
CONFIG_PACKAGE_ruby-psych=y
# CONFIG_PACKAGE_ruby-pty is not set
# CONFIG_PACKAGE_ruby-racc is not set
# CONFIG_PACKAGE_ruby-rake is not set
# CONFIG_PACKAGE_ruby-random_formatter is not set
# CONFIG_PACKAGE_ruby-rbconfig is not set
# CONFIG_PACKAGE_ruby-rbs is not set
# CONFIG_PACKAGE_ruby-rdoc is not set
# CONFIG_PACKAGE_ruby-readline is not set
# CONFIG_PACKAGE_ruby-readline-ext is not set
# CONFIG_PACKAGE_ruby-reline is not set
# CONFIG_PACKAGE_ruby-resolv is not set
# CONFIG_PACKAGE_ruby-resolv-replace is not set
# CONFIG_PACKAGE_ruby-rexml is not set
# CONFIG_PACKAGE_ruby-rinda is not set
# CONFIG_PACKAGE_ruby-ripper is not set
# CONFIG_PACKAGE_ruby-rjit is not set
# CONFIG_PACKAGE_ruby-rss is not set
# CONFIG_PACKAGE_ruby-ruby2_keywords is not set
# CONFIG_PACKAGE_ruby-securerandom is not set
# CONFIG_PACKAGE_ruby-set is not set
# CONFIG_PACKAGE_ruby-shellwords is not set
# CONFIG_PACKAGE_ruby-singleton is not set
# CONFIG_PACKAGE_ruby-socket is not set
CONFIG_PACKAGE_ruby-stringio=y
# CONFIG_PACKAGE_ruby-strscan is not set
# CONFIG_PACKAGE_ruby-syntax_suggest is not set
# CONFIG_PACKAGE_ruby-syslog is not set
# CONFIG_PACKAGE_ruby-tempfile is not set
# CONFIG_PACKAGE_ruby-testunit is not set
# CONFIG_PACKAGE_ruby-time is not set
# CONFIG_PACKAGE_ruby-timeout is not set
# CONFIG_PACKAGE_ruby-tmpdir is not set
# CONFIG_PACKAGE_ruby-tsort is not set
# CONFIG_PACKAGE_ruby-typeprof is not set
# CONFIG_PACKAGE_ruby-un is not set
# CONFIG_PACKAGE_ruby-unicodenormalize is not set
# CONFIG_PACKAGE_ruby-uri is not set
# CONFIG_PACKAGE_ruby-weakref is not set
CONFIG_PACKAGE_ruby-yaml=y
# CONFIG_PACKAGE_ruby-zlib is not set
# end of Ruby
```

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by xuexijiaoben** [comment]
我也是这个问题好久了

**Comment by xuexijiaoben** [comment]
我也是这个问题好久了

**Comment by xuexijiaoben** [comment]
make[3]: Entering directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/feeds/packages/libs/yaml'
make[3]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/feeds/packages/libs/yaml'
time: package/feeds/packages/yaml/host-compile#0.16#0.07#0.20
make[3]: Entering directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/feeds/packages/lang/ruby'
CFLAGS="-O2 -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/include" CPPFLAGS="-I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/include" CXXFLAGS="" LDFLAGS="-L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/lib -L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/lib -L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/lib" make -j1 -C /home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3  
make[4]: Entering directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3'
file2lastrev.rb: does not seem to be under a vcs: .
	BASERUBY = /usr/bin/ruby --disable=gems
	CC = ccache /home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/bin/gcc
	LD = ld
	LDSHARED = ccache /home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/bin/gcc -shared
	CFLAGS = -O2 -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/include 
	XCFLAGS = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -fexcess-precision=standard -DRUBY_EXPORT -I. -I.ext/include/x86_64-linux-gnu -I./include -I. -I./prism -I./enc/unicode/15.0.0  
	CPPFLAGS = -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/include -I/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/include   
	DLDFLAGS = -L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/host/lib -L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/hostpkg/lib -L/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/host/lib -Wl,--compress-debug-sections=zlib -fstack-protector-strong  
	SOLIBS = -lz -lrt -lrt -ldl -lcrypt -lm -lpthread 
	LANG = C
	LC_ALL = C
	LC_CTYPE = 
	MFLAGS = -w -j1
	RUSTC = rustc
	YJIT_RUSTC_ARGS = --crate-name=yjit --crate-type=staticlib --edition=2021 -g -C lto=thin -C opt-level=3 -C overflow-checks=on '--out-dir=/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3/yjit/target/release/' ./yjit/src/lib.rs
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

revision.h unchanged
generating x86_64-linux-gnu-fake.rb
x86_64-linux-gnu-fake.rb updated
generating enc.mk
making srcs under enc
make[5]: Entering directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3'
make[5]: Nothing to be done for 'srcs'.
make[5]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3'
generating transdb.h
transdb.h unchanged
linking static-library libruby-static.a
LLVM ERROR: Invalid encoding
make[4]: *** [Makefile:318: libruby-static.a] Aborted (core dumped)
make[4]: *** Deleting file 'libruby-static.a'
make[4]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3'
make[3]: *** [Makefile:1189: /home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/build_dir/hostpkg/ruby-3.3.3/.built] Error 2
make[3]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/feeds/packages/lang/ruby'
time: package/feeds/packages/ruby/host-compile#0.80#0.28#1.12
    ERROR: package/feeds/packages/ruby [host] failed to build.
make[2]: *** [package/Makefile:171: package/feeds/packages/ruby/host/compile] Error 1
make[2]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt'
make[1]: *** [package/Makefile:167: /home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt'
make: *** [/home/runner/work/My_immortalwrt/My_immortalwrt/openwrt/include/toplevel.mk:248: world] Error 2

**Comment by xuexijiaoben** [comment]
请问你解决这个问题了么

**Comment by liushuai05** [comment]
我也遇到了类似问题

**Comment by bcdi** [comment]
最新的 ruby v3.4.4 已经可以了

**Comment by luojixinhao** [comment]
> 最新的 ruby v3.4.4 已经可以了

还是不行：
Version：r27082-b733b6acb5
DEVICE_TARGET：ramips
DEVICE_SUBTARGET：mt7621
DEVICE_NAME：xiaomi_mi-router-3-pro
RepoURL：https://github.com/openwrt/openwrt
RepoBRANCH：main
TAG：SNAPSHOT

![image](https://github.com/user-attachments/assets/4378abfc-bcdb-4b49-b301-40902048ea0b)

**Comment by bcdi** [comment]
@luojixinhao 我跑的是armv7，可以通过

**Comment by greenice897** [comment]
> > 最新的 ruby v3.4.4 已经可以了
> 
> 还是不行： Version：r27082-b733b6acb5 DEVICE_TARGET：ramips DEVICE_SUBTARGET：mt7621 DEVICE_NAME：xiaomi_mi-router-3-pro RepoURL：https://github.com/openwrt/openwrt RepoBRANCH：main TAG：SNAPSHOT
> 
> ![image](https://private-user-images.githubusercontent.com/8543527/355455924-4378abfc-bcdb-4b49-b301-40902048ea0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMzk0NjUsIm5iZiI6MTcyMzMzOTE2NSwicGF0aCI6Ii84NTQzNTI3LzM1NTQ1NTkyNC00Mzc4YWJmYy1iY2RiLTRiNDktYjMwMS00MDkwMjA0OGVhMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDExOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZiMDVlNzk2YmQzMzIwYWVlNTMwMzdhMDFkYTQwM2Y5NDE4NDVhZWZkYWE2ZDg4MmM0ZjE5OGNiYWRkMDMwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.--zbkAIsA4ZaHSrHxpMafPgSqZI4jXYWTAjfBfcF6AM)

用ubuntu 24.04 可以通过

**Comment by luojixinhao** [comment]
> > > 最新的 ruby v3.4.4 已经可以了
> > 
> > 
> > 还是不行： Version：r27082-b733b6acb5 DEVICE_TARGET：ramips DEVICE_SUBTARGET：mt7621 DEVICE_NAME：xiaomi_mi-router-3-pro RepoURL：https://github.com/openwrt/openwrt RepoBRANCH：main TAG：SNAPSHOT
> > ![image](https://private-user-images.githubusercontent.com/8543527/355455924-4378abfc-bcdb-4b49-b301-40902048ea0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMzk0NjUsIm5iZiI6MTcyMzMzOTE2NSwicGF0aCI6Ii84NTQzNTI3LzM1NTQ1NTkyNC00Mzc4YWJmYy1iY2RiLTRiNDktYjMwMS00MDkwMjA0OGVhMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTFUMDExOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZiMDVlNzk2YmQzMzIwYWVlNTMwMzdhMDFkYTQwM2Y5NDE4NDVhZWZkYWE2ZDg4MmM0ZjE5OGNiYWRkMDMwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.--zbkAIsA4ZaHSrHxpMafPgSqZI4jXYWTAjfBfcF6AM)
> 
> 用ubuntu 24.04 可以通过

我用的就是ubuntu 24.04
![image](https://github.com/user-attachments/assets/f5ccc479-8ebd-458e-ab3a-05fdbdb5193a)

**Comment by xlighting2017** [comment]
> ### “我用的就是ubuntu 24.04”
<img width="589" alt="image" src="https://github.com/user-attachments/assets/e145727e-0a58-439d-8c0b-3c22103e29cb">

**Comment by luojixinhao** [comment]
> > ### “我用的就是ubuntu 24.04”
> 
> <img alt="image" width="589" src="https://private-user-images.githubusercontent.com/25970065/356845763-e145727e-0a58-439d-8c0b-3c22103e29cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDQ1MTMsIm5iZiI6MTcyMzM0NDIxMywicGF0aCI6Ii8yNTk3MDA2NS8zNTY4NDU3NjMtZTE0NTcyN2UtMGE1OC00MzlkLThjMGItM2MyMjEwM2UyOWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAyNDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YzRiODk0MzY0MDBmYzUxYmRjYzMxODcxMzQ0ZmFhMDA4N2VjNjhiMThkYzI2YTdkODcwMjM2MDZlNmRhYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESyYTEUlGZv_ynfM3cHWhHGsTtyuiLsroE1dybE4ooo">

哈哈，看错了

**Comment by smallprogram** [comment]
@luojixinhao 请问更换为24.04是否编译通过?

**Comment by smallprogram** [comment]
降到3.3.2没问题了

**Comment by BiGnotes** [comment]
> 降到3.3.2没问题了

请问3.3.2在哪下载啊？

**Comment by nodexbit32** [comment]
我遇到相同问题,
https://github.com/immortalwrt/packages/issues/1336
目前是降级到3.25解决的,也不知道是大库的问题还是ruby的问题

**Comment by MrEbonycat** [comment]
参照下面这里修改Makefile可以用Github Action编译成功。
https://github.com/openwrt/packages/pull/25151

**Comment by 1715173329** [comment]
upstream fixed
