### ISSUE TITLE
immortalwrt-23.05.2-x86-64-rootfs.tar.gz包缺少基础包导致opkg不可用

### ISSUE THREAD

**Issue by dunkeng** [immortalwrt/packages#1252]
缺少：zlib / libpcre2 / ca-certificates / wget
希望补充
以下是日志与验证：
root@Immortalwrt:~# opkg update
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/targets/x86/64/packages/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/targets/x86/64/packages/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/base/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/base/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/luci/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/luci/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/packages/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/packages/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/routing/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/routing/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/telephony/Packages.gz
wget: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/telephony/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/targets/x86/64/packages/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/base/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/luci/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/packages/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/routing/Packages.gz, wget returned 1.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/telephony/Packages.gz, wget returned 1.

root@Immortalwrt:~# opkg list-installed|grep -e zlib -e libpcre2 -e ca-certificates -e wget
root@Immortalwrt:~#

临时解决方案，自己下载了这几个包
root@Immortalwrt:/tmp# opkg install ./zlib_1.2.13-1_x86_64.ipk ./libpcre2_10.42-1_x86_64.ipk ./ca-certificates_20240203-1_all.ipk ./wget-ssl_1.21.4-1_x86_64.ipk
Installing zlib (1.2.13-1) to root...
Installing libpcre2 (10.42-1) to root...
Installing ca-certificates (20240203-1) to root...
Installing wget-ssl (1.21.4-1) to root...
Configuring libpcre2.
Configuring ca-certificates.
Configuring zlib.
Configuring wget-ssl.

然后可以用了
root@Immortalwrt:/tmp# opkg update
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/targets/x86/64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_core
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/targets/x86/64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/base/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_base
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/base/Packages.sig
Signature check passed.
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_luci
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/luci/Packages.sig
Signature check passed.
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_packages
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/packages/Packages.sig
Signature check passed.
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_routing
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/routing/Packages.sig
Signature check passed.
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/immortalwrt_telephony
Downloading https://mirrors.vsean.net/openwrt/releases/23.05.2/packages/x86_64/telephony/Packages.sig
Signature check passed.

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/immortalwrt/issues/1124
