### ISSUE TITLE
为啥opkg软件源中部分包的版本未同步github/packages中版本

### ISSUE THREAD

**Issue by 592732377** [immortalwrt/packages#1253]
系统信息: 
x86_64  QEMU  23.05.2 r27625-416c8c5c91
补充:
1、举个栗子：github/packages中Smartdns包在2周前更新到46版，但是23.05.2软件源中依然是45版本(7月3日更新)。
2、无论是release中部分包版本，还是immortalwrt官方其它软件源都一样现象。
3、只是想使用软件源图个方便，不想用SDK自己编译一次。
4、对github工作流不太了解，我看Actions中已编译通过了，不明白具体原因，特此请教大佬！

**Comment by 1715173329** [comment]
smartdns 仅提交到 master 主线分支，未进入 23.05 稳定分支。

**Comment by 592732377** [comment]
嗦嘎，忘记了分支。
十分感谢大佬答疑。
