### ISSUE TITLE
[package request] added mihomo package

### ISSUE THREAD

**Issue by douglarek** [immortalwrt/packages#1265]
I checked the repository and found that the clash package was removed a few weeks ago because the source code for clash itself is no longer maintained. I built the mihomo (formerly clash meta) package based on the clash package. Mihomo is actively developed. Are you interested in including it? I can submit a PR.

my mihomo package: https://github.com/douglarek/mihomo-openwrt .

**Comment by SerinaNya** [comment]
> my mihomo package: https://github.com/douglarek/mihomo-openwrt .

@douglarek Your project looks great! 

I’m really looking forward to mihomo. Could you open a PR?
