### ISSUE TITLE
软件包里的Alist有没有计划添加Https的支持？

### ISSUE THREAD

**Issue by laipeng668** [immortalwrt/packages#1274]
### Describe the bug

目前软件包安装的Alist没有办法添加ssl证书，所以开启不了Https，后续有没有计划添加支持？

### ImmortalWrt version

r0-d43b4e0

### ImmortalWrt release

SNAPSHOT

### ImmortalWrt target/subtarget

qualcommax/ipq60xx

### Device

JDCloud AX1800 Pro

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
没 luci = 没这个功能

**Comment by laipeng668** [comment]
有LuCI奥，只是LuCI界面没有添加证书的地方，config文件修改后，每次启动都会还原成初始值
![Snipaste_2024-07-24_20-21-25](https://github.com/user-attachments/assets/d4a2e5c1-fe8d-4600-9cb5-7eeab7ab4a4e)

**Comment by 1715173329** [comment]
luci 不打算设计此功能，如果需要就从命令行操作。

**Comment by laipeng668** [comment]
好的，谢谢啦！
