### ISSUE TITLE
ChinaDNS-NG 编译hash错误

### ISSUE THREAD

**Issue by chenxuan5858** [immortalwrt/packages#1275]
### Describe the bug

ChinaDNS-NG 编译hash错误

### ImmortalWrt version

Master

### ImmortalWrt release

Master

### ImmortalWrt target/subtarget

Master

### Device

X86

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
没日志，建议去街上找人给你算一命。

**Comment by 1715173329** [comment]
fixed
