### ISSUE TITLE
请升级下23.05 的go版本

### ISSUE THREAD

**Issue by jwkinko** [immortalwrt/packages#1282]
go: ../../go.mod requires go >= 1.22 (running go 1.21.12; GOTOOLCHAIN=local)
Building targets
go: ../../go.mod requires go >= 1.22 (running go 1.21.12; GOTOOLCHAIN=local)
make[3]: *** [Makefile:44: /home/qqat/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.15.1/.built] Error 1
make[3]: Leaving directory '/home/qqat/immortalwrt/feeds/passwall_packages/v2ray-plugin'
time: package/feeds/passwall_packages/v2ray-plugin/compile#0.20#0.18#0.46
    ERROR: package/feeds/passwall_packages/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:129: package/feeds/passwall_packages/v2ray-plugin/compile] Error 1

**Comment by 1715173329** [comment]
稳定分支不会做工具链的 major update，使用第三方 feeds 造成的问题自行负责。
