### ISSUE TITLE
master 分支 vsftp 无法启动

### ISSUE THREAD

**Issue by imoldchen** [immortalwrt/packages#131]
在终端手动启动 /etc/init.d/vsftpd restart 提示错误（恢复默认配置文件依旧）
500 OOPS: unrecognised variable in config file: uci_config_name

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/packages/blob/d8336c805f4de80ed3a773d2617b74df269e87b4/net/vsftpd/files/vsftpd_prepare#L229
试试将这一行注释掉

**Comment by imoldchen** [comment]
> https://github.com/immortalwrt/packages/blob/d8336c805f4de80ed3a773d2617b74df269e87b4/net/vsftpd/files/vsftpd_prepare#L229
> 
> 
> 试试将这一行注释掉

注释之后 OK 了。
