### ISSUE TITLE
qBittorrent日志无法打印生成的随机密码

### ISSUE THREAD

**Issue by yyshell** [immortalwrt/packages#1327]
qBittorrent好久不用了，最近想用的时候，发现默认的admin用户已无法登录。
尝试了各种网上的方法，例如生成新的加盐哈希过的密码，更改配置等等，都无法再次登录了。
qBittorrent在openwrt下无法打印生成的随机密码，这个程序现在还在等官方修复中吗？

**Comment by yyshell** [comment]
导致的问题就是，新安装的qbittorrent，上来就无法登录使用

**Comment by 1715173329** [comment]
daemon 默认生成的用户名和密码就是 admin 和 adminadmin。

**Comment by yyshell** [comment]
全新安装的情况下，启动qbittorrent，登录提示Invalid Username or Password.

**Comment by 1715173329** [comment]
使用内置的 init 服务。

**Comment by yyshell** [comment]
发现问题的进展了，登录后，后台提示：WebAPI login success. IP：192.168.xxxx
然后qbittorrent进程退出了

**Comment by yyshell** [comment]
确切地说是，WebAPI login success. IP: ::ffff:192.168
这个和IPV6应该没有关系吧？
