### ISSUE TITLE
qbittorrent登录后崩溃

### ISSUE THREAD

**Issue by yyshell** [immortalwrt/packages#1332]
qbittorrent web ui一旦登录后，应用日志提示：
 WebAPI login success. IP: ::ffff:192.168.xx.xx
然后无法登录。进入ssh后，发现进程已经退出。
下面是系统日志：
Thu Sep 19 22:47:29 2024 daemon.err qbittorrent-nox[30542]: QObject::startTimer: Timers cannot be started from another thread
Thu Sep 19 22:47:49 2024 daemon.err qbittorrent-nox[30542]: pure virtual method called
Thu Sep 19 22:47:49 2024 daemon.err qbittorrent-nox[30542]: terminate called without an active exception
Thu Sep 19 22:47:49 2024 daemon.info procd: Instance qbittorrent::instance1 s in a crash loop 10 crashes, 20 seconds since last crash
Thu Sep 19 22:47:58 2024 daemon.err qbittorrent-nox[30649]: QObject::startTimer: Timers cannot be started from another thread
Thu Sep 19 22:48:12 2024 daemon.err qbittorrent-nox[30649]: pure virtual method called
Thu Sep 19 22:48:12 2024 daemon.err qbittorrent-nox[30649]: terminate called without an active exception
Thu Sep 19 22:48:12 2024 daemon.info procd: Instance qbittorrent::instance1 s in a crash loop 11 crashes, 15 seconds since last crash
Thu Sep 19 22:51:46 2024 daemon.err qbittorrent-nox[30834]: QObject::startTimer: Timers cannot be started from another thread
Thu Sep 19 22:52:16 2024 daemon.err qbittorrent-nox[30834]: pure virtual method called
Thu Sep 19 22:52:16 2024 daemon.err qbittorrent-nox[30834]: terminate called without an active exception
Thu Sep 19 22:52:16 2024 daemon.info procd: Instance qbittorrent::instance1 s in a crash loop 12 crashes, 31 seconds since last crash

**Comment by 1715173329** [comment]
会自己编译的话，revert 这两条 commit 然后 make clean 重新编译试试
70369e466f86f4a34e13b50d9d69d5a83fcacdaa
8fd7bd50c0ae9e7006386bb04304ee2e77e6a8f4

**Comment by 1715173329** [comment]
固件什么版本

**Comment by yyshell** [comment]
git pull最新的版本，x86的

**Comment by yyshell** [comment]
> 会自己编译的话，revert 这两条 commit 然后 make clean 重新编译试试 [70369e4](https://github.com/immortalwrt/packages/commit/70369e466f86f4a34e13b50d9d69d5a83fcacdaa) [8fd7bd5](https://github.com/immortalwrt/packages/commit/8fd7bd50c0ae9e7006386bb04304ee2e77e6a8f4)

revert不了，fatal error。

**Comment by 1715173329** [comment]
```patch
diff --git a/libs/qt6base/Makefile b/libs/qt6base/Makefile
index e550a6096c..3312252d2e 100644
--- a/libs/qt6base/Makefile
+++ b/libs/qt6base/Makefile
@@ -8,16 +8,16 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=qt6base
-PKG_BASE:=6.2
-PKG_BUGFIX:=9
+PKG_BASE:=6.5
+PKG_BUGFIX:=3
 PKG_VERSION:=$(PKG_BASE).$(PKG_BUGFIX)
 PKG_RELEASE:=1
 
-PKG_SOURCE:=qtbase-everywhere-opensource-src-$(PKG_VERSION).tar.xz
-PKG_SOURCE_URL:=https://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
-		https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
-		https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
-PKG_HASH:=494154ebbb00d26ef556b4389466354aa2fa5a0e145841fd915b5f3005fe719c
+PKG_SOURCE:=qtbase-everywhere-src-$(PKG_VERSION).tar.xz
+PKG_SOURCE_URL:=https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
+		  https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
+		  http://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
+PKG_HASH:=df2f4a230be4ea04f9798f2c19ab1413a3b8ec6a80bef359f50284235307b546
 
 HOST_BUILD_DIR:=$(BUILD_DIR_HOST)/qtbase-everywhere-src-$(PKG_VERSION)
 PKG_BUILD_DIR:=$(BUILD_DIR)/qtbase-everywhere-src-$(PKG_VERSION)
diff --git a/libs/qt6base/patches/010-marco.patch b/libs/qt6base/patches/010-marco.patch
new file mode 100644
index 0000000000..6abac5e9e2
--- /dev/null
+++ b/libs/qt6base/patches/010-marco.patch
@@ -0,0 +1,12 @@
+--- a/src/corelib/plugin/qelfparser_p.cpp
++++ b/src/corelib/plugin/qelfparser_p.cpp
+@@ -382,7 +382,9 @@ Q_DECL_UNUSED Q_DECL_COLD_FUNCTION stati
+     case EM_ALPHA:      d << ", Alpha"; break;
+     case EM_68K:        d << ", MC68000"; break;
+     case EM_ARM:        d << ", ARM"; break;
++#ifdef EM_AARCH64
+     case EM_AARCH64:    d << ", AArch64"; break;
++#endif
+ #ifdef EM_BLACKFIN
+     case EM_BLACKFIN:   d << ", Blackfin"; break;
+ #endif
diff --git a/utils/qt6tools/Makefile b/utils/qt6tools/Makefile
index 6d9c659834..4846b7f862 100644
--- a/utils/qt6tools/Makefile
+++ b/utils/qt6tools/Makefile
@@ -8,16 +8,16 @@
 include $(TOPDIR)/rules.mk
 
 PKG_NAME:=qt6tools
-PKG_BASE:=6.2
-PKG_BUGFIX:=9
+PKG_BASE:=6.5
+PKG_BUGFIX:=3
 PKG_VERSION:=$(PKG_BASE).$(PKG_BUGFIX)
 PKG_RELEASE:=1
 
-PKG_SOURCE:=qttools-everywhere-opensource-src-$(PKG_VERSION).tar.xz
-PKG_SOURCE_URL:=https://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
-		https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
-		https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
-PKG_HASH:=b91bfbec153054752a9ea06bfb92024b8ca2bb0f6e16c02d4d4a7bebc8193f1a
+PKG_SOURCE:=qttools-everywhere-src-$(PKG_VERSION).tar.xz
+PKG_SOURCE_URL:=https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
+		  https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
+		  http://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
+PKG_HASH:=fc91d32b3f696725bbb48b0df240c25b606bbee3bd22627cfcbee876a6405e37
 HOST_BUILD_DIR:=$(BUILD_DIR_HOST)/qttools-everywhere-src-$(PKG_VERSION)
 
 PKG_MAINTAINER:=Krypton Lee <jun.k.lee199410@outlook.com>
diff --git a/utils/qt6tools/patches/010-no-clang.patch b/utils/qt6tools/patches/010-no-clang.patch
index 94b2e3a16e..674f25ecca 100644
--- a/utils/qt6tools/patches/010-no-clang.patch
+++ b/utils/qt6tools/patches/010-no-clang.patch
@@ -1,6 +1,6 @@
 --- a/configure.cmake
 +++ b/configure.cmake
-@@ -16,7 +16,7 @@
+@@ -17,7 +17,7 @@
  # Presumably because 6.0 ClangConfig.cmake files are not good enough?
  # In any case explicitly request a minimum version of 8.x for now, otherwise
  # building with CMake will fail at compilation time.
```

在 feeds/packages 目录下面 patch 这个补丁

**Comment by yyshell** [comment]
> ```diff
> diff --git a/libs/qt6base/Makefile b/libs/qt6base/Makefile
> index e550a6096c..3312252d2e 100644
> --- a/libs/qt6base/Makefile
> +++ b/libs/qt6base/Makefile
> @@ -8,16 +8,16 @@
>  include $(TOPDIR)/rules.mk
>  
>  PKG_NAME:=qt6base
> -PKG_BASE:=6.2
> -PKG_BUGFIX:=9
> +PKG_BASE:=6.5
> +PKG_BUGFIX:=3
>  PKG_VERSION:=$(PKG_BASE).$(PKG_BUGFIX)
>  PKG_RELEASE:=1
>  
> -PKG_SOURCE:=qtbase-everywhere-opensource-src-$(PKG_VERSION).tar.xz
> -PKG_SOURCE_URL:=https://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> -		https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> -		https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
> -PKG_HASH:=494154ebbb00d26ef556b4389466354aa2fa5a0e145841fd915b5f3005fe719c
> +PKG_SOURCE:=qtbase-everywhere-src-$(PKG_VERSION).tar.xz
> +PKG_SOURCE_URL:=https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> +		  https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> +		  http://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
> +PKG_HASH:=df2f4a230be4ea04f9798f2c19ab1413a3b8ec6a80bef359f50284235307b546
>  
>  HOST_BUILD_DIR:=$(BUILD_DIR_HOST)/qtbase-everywhere-src-$(PKG_VERSION)
>  PKG_BUILD_DIR:=$(BUILD_DIR)/qtbase-everywhere-src-$(PKG_VERSION)
> diff --git a/libs/qt6base/patches/010-marco.patch b/libs/qt6base/patches/010-marco.patch
> new file mode 100644
> index 0000000000..6abac5e9e2
> --- /dev/null
> +++ b/libs/qt6base/patches/010-marco.patch
> @@ -0,0 +1,12 @@
> +--- a/src/corelib/plugin/qelfparser_p.cpp
> ++++ b/src/corelib/plugin/qelfparser_p.cpp
> +@@ -382,7 +382,9 @@ Q_DECL_UNUSED Q_DECL_COLD_FUNCTION stati
> +     case EM_ALPHA:      d << ", Alpha"; break;
> +     case EM_68K:        d << ", MC68000"; break;
> +     case EM_ARM:        d << ", ARM"; break;
> ++#ifdef EM_AARCH64
> +     case EM_AARCH64:    d << ", AArch64"; break;
> ++#endif
> + #ifdef EM_BLACKFIN
> +     case EM_BLACKFIN:   d << ", Blackfin"; break;
> + #endif
> diff --git a/utils/qt6tools/Makefile b/utils/qt6tools/Makefile
> index 6d9c659834..4846b7f862 100644
> --- a/utils/qt6tools/Makefile
> +++ b/utils/qt6tools/Makefile
> @@ -8,16 +8,16 @@
>  include $(TOPDIR)/rules.mk
>  
>  PKG_NAME:=qt6tools
> -PKG_BASE:=6.2
> -PKG_BUGFIX:=9
> +PKG_BASE:=6.5
> +PKG_BUGFIX:=3
>  PKG_VERSION:=$(PKG_BASE).$(PKG_BUGFIX)
>  PKG_RELEASE:=1
>  
> -PKG_SOURCE:=qttools-everywhere-opensource-src-$(PKG_VERSION).tar.xz
> -PKG_SOURCE_URL:=https://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> -		https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> -		https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
> -PKG_HASH:=b91bfbec153054752a9ea06bfb92024b8ca2bb0f6e16c02d4d4a7bebc8193f1a
> +PKG_SOURCE:=qttools-everywhere-src-$(PKG_VERSION).tar.xz
> +PKG_SOURCE_URL:=https://mirrors.tencent.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> +		  https://mirrors.aliyun.com/qt/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/ \
> +		  http://download.qt-project.org/archive/qt/$(PKG_BASE)/$(PKG_VERSION)/submodules/
> +PKG_HASH:=fc91d32b3f696725bbb48b0df240c25b606bbee3bd22627cfcbee876a6405e37
>  HOST_BUILD_DIR:=$(BUILD_DIR_HOST)/qttools-everywhere-src-$(PKG_VERSION)
>  
>  PKG_MAINTAINER:=Krypton Lee <jun.k.lee199410@outlook.com>
> diff --git a/utils/qt6tools/patches/010-no-clang.patch b/utils/qt6tools/patches/010-no-clang.patch
> index 94b2e3a16e..674f25ecca 100644
> --- a/utils/qt6tools/patches/010-no-clang.patch
> +++ b/utils/qt6tools/patches/010-no-clang.patch
> @@ -1,6 +1,6 @@
>  --- a/configure.cmake
>  +++ b/configure.cmake
> -@@ -16,7 +16,7 @@
> +@@ -17,7 +17,7 @@
>   # Presumably because 6.0 ClangConfig.cmake files are not good enough?
>   # In any case explicitly request a minimum version of 8.x for now, otherwise
>   # building with CMake will fail at compilation time.
> ```
> 
> 在 feeds/packages 目录下面 patch 这个补丁

Dear Dashen, it works. You saved my life. Thank you.
