### ISSUE TITLE
fibocom-qmi-wwan云编译失败

### ISSUE THREAD

**Issue by daitcl** [immortalwrt/packages#1333]
make[2] -C feeds/packages/kernel/fibocom-qmi-wwan download
 make[2] -C feeds/packages/net/etherwake download
    ERROR: package/feeds/packages/fibocom-qmi-wwan failed to build.

make[3] -C feeds/packages/kernel/fibocom-qmi-wwan clean-build
 make[3] -C feeds/packages/kernel/fibocom-qmi-wwan compile
    ERROR: package/feeds/packages/fibocom-qmi-wwan failed to build

**Comment by xlighting2017** [comment]
我这里是好的
<img width="626" alt="image" src="https://github.com/user-attachments/assets/a7ca4fdc-7700-49f8-a0dd-9961f2bfdc5e">

**Comment by daitcl** [comment]
> 我这里是好的 <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/25970065/369214709-a7ca4fdc-7700-49f8-a0dd-9961f2bfdc5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDA2OTEsIm5iZiI6MTcyNjgwMDM5MSwicGF0aCI6Ii8yNTk3MDA2NS8zNjkyMTQ3MDktYTdjYTRmZGMtNzcwMC00OWY4LWEwZGQtOTk2MWYyYmZkYzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyNDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNzYxNWYwOTQ1NjJhMDdmNTFiNzFiMzcyMTVjOTkwMjI1MzA3ODc1ODVmYmQ2ZDhjOWRmYTlmYTVjZWZmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6a3YP1GN2aKTrkIq3tTS4A7XCxIbuHAlyQQSrk9s5rI">

你是怎么选的呀，我也没勾选这个，但是显示下载不了，然后编译失败

**Comment by xlighting2017** [comment]
那就是  你的配置不对， 你先贴出所有的配置，才能知道哪里不对

如果你不知道/不确认什么是 “所有的配置”， 那就别编了

直接用 firmware selector，参考此文档：https://github.com/immortalwrt/user-FAQ

**Comment by 1715173329** [comment]
完整日志呢？

**Comment by daitcl** [comment]
> 那就是 你的配置不对， 你先贴出所有的配置，才能知道哪里不对
> 
> 如果你不知道/不确认什么是 “所有的配置”， 那就别编了
> 
> 直接用 firmware selector，参考此文档：https://github.com/immortalwrt/user-FAQ

CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
CONFIG_DEVEL=y
CONFIG_AUTOREMOVE=y
CONFIG_BPF_TOOLCHAIN_BUILD_LLVM=y
# CONFIG_BPF_TOOLCHAIN_NONE is not set
CONFIG_BUILDBOT=y
CONFIG_COLLECT_KERNEL_DEBUG=y
CONFIG_DOCKER_CGROUP_OPTIONS=y
CONFIG_DOCKER_NET_MACVLAN=y
CONFIG_DOCKER_STO_EXT4=y
CONFIG_HAS_BPF_TOOLCHAIN=y
CONFIG_IB=y
CONFIG_IMAGEOPT=y
CONFIG_JSON_CYCLONEDX_SBOM=y
CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
CONFIG_KERNEL_BUILD_USER="builder"
CONFIG_KERNEL_CGROUP_DEVICE=y
CONFIG_KERNEL_CGROUP_FREEZER=y
CONFIG_KERNEL_CGROUP_NET_PRIO=y
CONFIG_KERNEL_EXT4_FS_POSIX_ACL=y
CONFIG_KERNEL_EXT4_FS_SECURITY=y
CONFIG_KERNEL_FS_POSIX_ACL=y
# CONFIG_KERNEL_KALLSYMS is not set
CONFIG_KERNEL_NET_CLS_CGROUP=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_CRYPTO_AUTH=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_NGHTTP2=y
CONFIG_LIBCURL_OPENSSL=y
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_TFTP=y
CONFIG_LIBCURL_THREADED_RESOLVER=y
CONFIG_LIBCURL_TLS_SRP=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LUCI_LANG_zh_Hans=y
CONFIG_MAKE_TOOLCHAIN=y
CONFIG_NODEJS_ICU_SMALL=y
CONFIG_PACKAGE_TAR_BZIP2=y
CONFIG_PACKAGE_TAR_GZIP=y
CONFIG_PACKAGE_TAR_XZ=y
CONFIG_PACKAGE_TAR_ZSTD=y
CONFIG_PACKAGE_WECHATPUSH_Enable_Host_Information_Detection=y
CONFIG_PACKAGE_WECHATPUSH_Enable_Local_Disk_Information_Detection=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_blkid=y
CONFIG_PACKAGE_btrfs-progs=y
CONFIG_PACKAGE_bzip2=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_cgroupfs-mount=y
CONFIG_PACKAGE_containerd=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_coreutils-stat=y
CONFIG_PACKAGE_coreutils-stty=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_ddns-go=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_dnsmasq_full_tftp=y
CONFIG_PACKAGE_docker=y
CONFIG_PACKAGE_docker-compose=y
CONFIG_PACKAGE_dockerd=y
CONFIG_PACKAGE_etherwake=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_ip6tables-extra=y
CONFIG_PACKAGE_ip6tables-mod-nat=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_iptables-mod-filter=y
CONFIG_PACKAGE_iptables-mod-nat-extra=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_iputils-arping=y
CONFIG_PACKAGE_jq=y
CONFIG_PACKAGE_kmod-br-netfilter=y
CONFIG_PACKAGE_kmod-dummy=y
CONFIG_PACKAGE_kmod-fs-btrfs=y
CONFIG_PACKAGE_kmod-ifb=y
CONFIG_PACKAGE_kmod-inet-diag=y
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ip6tables-extra=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-extra=y
CONFIG_PACKAGE_kmod-ipt-filter=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-nat-extra=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
CONFIG_PACKAGE_kmod-ipt-physdev=y
CONFIG_PACKAGE_kmod-lib-raid6=y
CONFIG_PACKAGE_kmod-lib-textsearch=y
CONFIG_PACKAGE_kmod-lib-xor=y
CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
CONFIG_PACKAGE_kmod-lib-zstd=y
CONFIG_PACKAGE_kmod-macvlan=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-ipvs=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-nf-tproxy=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nft-fullcone=y
CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_kmod-sched=y
CONFIG_PACKAGE_kmod-sched-core=y
CONFIG_PACKAGE_kmod-tcp-bbr=y
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-veth=y
CONFIG_PACKAGE_knot-resolver_dnstap=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libattr=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libbz2=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcap-bin=y
CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
CONFIG_PACKAGE_libcares=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libiwinfo=y
CONFIG_PACKAGE_libiwinfo-data=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblzma=y
CONFIG_PACKAGE_liblzo=y
CONFIG_PACKAGE_libmount=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libparted=y
CONFIG_PACKAGE_libpcap=m
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_libruby=y
CONFIG_PACKAGE_libseccomp=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuci-lua=y
CONFIG_PACKAGE_libuv=y
CONFIG_PACKAGE_libwebsockets-full=y
CONFIG_PACKAGE_libxdp=m
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE

**Comment by daitcl** [comment]
> 完整日志呢？

time: package/feeds/packages/etherwake/download#0.10#0.11#0.18
make[2]: Entering directory '/workdir/openwrt/feeds/packages/kernel/fibocom-qmi-wwan'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.fibocom-qmi-wwan-1.0.5.tar.gz.flock -c '  	echo "ERROR: No download method available"; false'
ERROR: No download method available
make[2]: *** [Makefile:30: /workdir/openwrt/dl/fibocom-qmi-wwan-1.0.5.tar.gz] Error 1
make[2]: Leaving directory '/workdir/openwrt/feeds/packages/kernel/fibocom-qmi-wwan'
time: package/feeds/packages/fibocom-qmi-wwan/download#0.07#0.10#0.15
    ERROR: package/feeds/packages/fibocom-qmi-wwan failed to build.
make[1]: *** [package/Makefile:128: package/feeds/packages/fibocom-qmi-wwan/download] Error 1
make[1]: Leaving directory '/workdir/openwrt'
make[1]: Entering directory '/workdir/openwrt'
cd "/workdir/openwrt"; git log --format=%h -1 toolchain > /workdir/openwrt/tmp/.ver_check
cmp -s /workdir/openwrt/tmp/.ver_check /workdir/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/stamp/.ver_check || { \
	rm -rf /workdir/openwrt/build_dir/target-x86_64_musl /workdir/openwrt/staging_dir/target-x86_64_musl /workdir/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl /workdir/openwrt/build_dir/toolchain-x86_64_gcc-12.3.0_musl; \
	mkdir -p /workdir/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/stamp; \
	mv /workdir/openwrt/tmp/.ver_check /workdir/openwrt/staging_dir/toolchain-x86_64_gcc-12.3.0_musl/stamp/.ver_check; \
}
make[2]: Entering directory '/workdir/openwrt/target/linux'

download的时候就出错了

**Comment by 1715173329** [comment]
鉴定为非 immortalwrt 核心源码，要使用 wwan 包，可以引用 <https://github.com/immortalwrt/wwan-packages>。

**Comment by daitcl** [comment]
> 鉴定为非 immortalwrt 核心源码，要使用 wwan 包，可以引用 https://github.com/immortalwrt/wwan-packages。

这个可以直接git clone 到 packages文件夹里吗？ 还是要添加进 feeds?

**Comment by 1715173329** [comment]
都可以。

**Comment by daitcl** [comment]
> 都可以。

.感谢，我这就去试
