### ISSUE TITLE
dae: request package update on v23.05 branch

### ISSUE THREAD

**Issue by Integral-Tech** [immortalwrt/packages#1369]
Maintainer: @1715173329 (find it by checking history of the package Makefile)
Environment: Cortex-A53, Xiaomi Redmi Router AX6000 (OpenWrt U-Boot layout), 23.05.4

Description:

- dae on v23.05 branch hasn't been updated since v0.6.0. The upstream latest stable release is [v0.8.0](https://github.com/daeuniverse/dae/releases/tag/v0.8.0), which has introduced quite a few new features including support for new proxy protocols since v0.6.0. Therefore, it would better to update dae on v23.05 branch to v0.8.0.

**Comment by 1715173329** [comment]
Impossible to update as it requires newer go toolchain.

**Comment by Integral-Tech** [comment]
> Impossible to update as it requires newer go toolchain.

The version of [go toolchain on branch v23.05](https://github.com/daeuniverse/dae/blob/v0.7.4/docs/en/user-guide/build-by-yourself.md) is 1.21.

Although dae v0.8.0 requires minimum version 1.22 for golang, [v0.7.4](https://github.com/daeuniverse/dae/blob/v0.7.4/docs/en/user-guide/build-by-yourself.md) only requires v1.18. Is it possible to update dae to v0.7.4?

**Comment by 1715173329** [comment]
go.mod says no.
