### ISSUE TITLE
同步最新源码 vlmcsd 编译失败

### ISSUE THREAD

**Issue by mitsukileung** [immortalwrt/packages#1375]
X86架构
master分支

# Move conffiles to IDIR and build conffiles_static with csums
if [ -f /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/apk-x86_64/vlmcsd/conffiles ]; then mv -f /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/apk-x86_64/vlmcsd/conffiles /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/lib/apk/packages/vlmcsd.conffiles; for file in $(cat /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/lib/apk/packages/vlmcsd.conffiles); do [ -f /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/$file ] || continue; csum=$(/workdir/openwrt/staging_dir/host/bin/mkhash sha256 /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/$file); echo $file $csum >> /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/lib/apk/packages/vlmcsd.conffiles_static; done; fi
# Some package (base-files) manually append stuff to conffiles
# Append stuff from it and delete the CONTROL directory since everything else should be migrated
if [ -f /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL/conffiles ]; then echo $(IDIR_vlmcsd)/CONTROL/conffiles >> /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/lib/apk/packages/vlmcsd.conffiles; for file in $(cat /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL/conffiles); do [ -f /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/$file ] || continue; csum=$(/workdir/openwrt/staging_dir/host/bin/mkhash sha256 /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/$file); echo $file $csum >> /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/lib/apk/packages/vlmcsd.conffiles_static; done; rm -rf /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL/conffiles; fi
if [ -z "$(ls -A /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL 2>/dev/null)" ]; then rm -rf /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL; else echo "CONTROL directory /workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd/CONTROL is not empty! This is not right and should be checked!" >&2; exit 1; fi
/workdir/openwrt/staging_dir/host/bin/fakeroot /workdir/openwrt/staging_dir/host/bin/apk mkpkg --info "name:vlmcsd" --info "version:svn1113-r3" --info "description:KMS Emulator in C (currently runs on Linux including Android, FreeBSD, Solaris, Minix, Mac OS, iOS, Windows with or without Cygwin)" --info "arch:x86_64" --info "license:MIT" --info "origin:feeds/packages/net/vlmcsd" --info "url:https://github.com/Wind4/vlmcsd" --info "maintainer:fuyumi <280604399@qq.com>" --info "provides:"  --script "post-install:/workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/apk-x86_64/vlmcsd/post-install" --script "pre-deinstall:/workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/apk-x86_64/vlmcsd/pre-deinstall" --info "depends:libc libpthread" --files "/workdir/openwrt/build_dir/target-x86_64_musl/vlmcsd-svn1113/ipkg-x86_64/vlmcsd" --output "/workdir/openwrt/bin/packages/x86_64/packages/vlmcsd-svn1113-r3.apk" --sign "/workdir/openwrt/private-key.pem"
ERROR: info field 'version' has invalid value: package version is invalid
ERROR: failed to create package: /workdir/openwrt/bin/packages/x86_64/packages/vlmcsd-svn1113-r3.apk: package version is invalid
make[3]: *** [Makefile:83: /workdir/openwrt/bin/packages/x86_64/packages/vlmcsd-svn1113-r3.apk] Error 99
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/net/vlmcsd'
time: package/feeds/packages/vlmcsd/compile#0.23#0.11#0.32
    ERROR: package/feeds/packages/vlmcsd failed to build.
make[2]: *** [package/Makefile:179: package/feeds/packages/vlmcsd/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:173: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

**Comment by davidtall** [comment]
same issue A53 遇到同样的问题
