### ISSUE TITLE
可以更新一下23.05的alist吗？

### ISSUE THREAD

**Issue by pugaizai** [immortalwrt/packages#1412]
现在的版本用着有些问题

**Comment by rianjskis** [comment]
24.10也请求更新到3.40，现在的版本挂载后播放有问题，谢谢天灵佬

**Comment by pugaizai** [comment]
> 24.10也请求更新到3.40，现在的版本挂载后播放有问题，谢谢天灵佬

下载官方repo的releases替换二进制就好了
