### ISSUE TITLE
aliyun DDNS not included in 21.0.2

### ISSUE THREAD

**Issue by hehe9011** [immortalwrt/packages#161]
Hi, there is no aliyun DDNS in 21.0.2 DDNS scripts, could you add it

**Comment by 1715173329** [comment]
Isn't it here?
https://github.com/immortalwrt/packages/tree/openwrt-21.02/net/ddns-scripts_aliyun

**Comment by hehe9011** [comment]
Thank you for your kindly reply.
I mean in Luci's application, there is no aliddns included in the ddns scripts.




At 2021-10-24 16:37:14, "Tianling Shen" ***@***.***> wrote:

Isn't it here?
https://github.com/immortalwrt/packages/tree/openwrt-21.02/net/ddns-scripts_aliyun

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1715173329** [comment]
> Thank you for your kindly reply.
> I mean in Luci's application, there is no aliddns included in the ddns scripts.

Isn't it in luci-app-ddns?
BTW I have no idea if aliddns works in master branch. If not I can port ddns-go here.

**Comment by hehe9011** [comment]
I chosed 21.02 branch and seems there is no aliddns in ddns script?




在 2021-10-30 18:50:08，"Tianling Shen" ***@***.***> 写道：

Thank you for your kindly reply.
I mean in Luci's application, there is no aliddns included in the ddns scripts.

Isn't it in luci-app-ddns?
BTW I have no idea if aliddns works in master branch. If not I can port ddns-go here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1715173329** [comment]
1. select `luci-app-ddns` in `LuCI -> 3. Applications`
2. select `ddns-scripts_aliyun` in `Network -> IP Addresses and Names`

**Comment by hehe9011** [comment]
that works, thank you!
















在 2021-10-30 22:40:46，"Tianling Shen" ***@***.***> 写道：

select luci-app-ddns in LuCI -> 3. Applications
select ddns-scripts_aliyun in Network -> IP Addresses and Names

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1715173329** [comment]
Not at all ;)
