### ISSUE TITLE
libsodium update breaks pynacl compile on branch 21.02

### ISSUE THREAD

**Issue by kongscn** [immortalwrt/packages#171]
a libsodium update merged into 21.02 branch breaks pynacal compile, see this [commit](https://github.com/openwrt/packages/commit/ccd3b6c0a5e15822b66b07524639b24753f7aea3#diff-b62da13e398ff67124150592596a2d274c814076b1df8b9853556ff9fa490f27) from upstream

**Comment by 1715173329** [comment]
Thanks, fixed now.
