### ISSUE TITLE
qBittorrent 上传种子文件 程序自动关闭

### ISSUE THREAD

**Issue by screenshot-zz** [immortalwrt/packages#192]
qBittorrent 上传种子文件 程序自动关闭
然后系统日志提示
Mon Nov 15 18:11:26 2021 kern.info kernel: [53494.191117] traps: qbittorrent-nox[6119] general protection ip:7f0a89d7c9eb sp:7f0a885b1ae8 error:0 in libc.so[7f0a89d6d000+49000]

然后qBittorrent就无法打开  只能把/etc/qBittorrent/data/BT_backup里的种子文件删了才能打开

**Comment by kendraase** [comment]
额，有人提这个问题啊，
题主描述不完全对，不是上传种子文件后，是只要开始下载就有概率出现。
再说下我的发现

1、仅出现在18.06上，无论是原版还是EE版本会出现；
2、出现在4.3.X之后（好像是4.3.5），所以18.06用4.2.X及之前的版本没问题；
3、和libtorrent版本无关；
4、tracker越少时，一次打开能运行的时间越长，但100%会触发。就是时间问题。无tracker纯靠dht也一样。（仅个人、单设备测试）。

**Comment by kendraase** [comment]
顺便再说个相关的。
4.3.7以后的版本会出现weiui无法管理种子，页面半空白，但是实际会后台下载的情况。（同样原版和EE版本都有）（应该是占用率过高的问题，qbt有类似issue。）
所以建议暂时18.06维持版本在4.2.5，其它的为4.3.6。

**Comment by screenshot-zz** [comment]
我现在把Lean 的qt 和 qBittorrent 替换了 编译成功了  功能正常 暂时没发现问题     随便牢骚一句  我用action 编译 凡是编译需要node 或者 golang  的  通通超过6小时导致失败

**Comment by noorall** [comment]
貌似是boost库的问题，在其他衍生版发现了类似的问题，这里是解决方案
https://github.com/coolsnowwolf/lede/issues/8663

**Comment by 1715173329** [comment]
可以试一下新版现在情况如何了。

**Comment by 1368129224** [comment]
请问在哪安装官方版的qBittorrent？
某些网站禁止使用Enhanced-Edition

**Comment by 1368129224** [comment]
希望添加原版qBittorrent，与Enhanced-Edition做一下区分，感谢！

**Comment by 1715173329** [comment]
我们修改了 qbee 的 header，使之与原版一致，应当不会产生影响。

**Comment by 1368129224** [comment]
> 我们修改了 qbee 的 header，使之与原版一致，应当不会产生影响。

好的，明白了，非常感谢！
