### ISSUE TITLE
这是哪里有问题？朋友们，

### ISSUE THREAD

**Issue by tao593** [immortalwrt/packages#194]
daemon.err AdGuardHome[6270]: panic: qtls.CertificateRequestInfo doesn't match
daemon.err AdGuardHome[6270]:
daemon.err AdGuardHome[6270]: goroutine 1 [running]:
daemon.err AdGuardHome[6270]: github.com/marten-seemann/qtls-go1-16.init.0()
daemon.err AdGuardHome[6270]: 	github.com/marten-seemann/qtls-go1-16@v0.1.3/unsafe.go:17 +0x248

**Comment by 1715173329** [comment]
这是因为 AdGuardHome 迟迟不肯发新 release 版本，现有的最新 release 版本与 go 1.17 不兼容。

**Comment by tao593** [comment]
。。。为什么替换核心就好了呢，我就好奇。

> 这是 AdGuardHome 迟迟不肯发新版本，现有的最新版本是 1.17，因为不知道。

**Comment by tao593** [comment]
替换/user/bin/的核心就好了。特奇怪
