### ISSUE TITLE
lang 下面的 python3 ruby 都编译失败

### ISSUE THREAD

**Issue by imoldchen** [immortalwrt/packages#365]
openwrt-21.02 分支

python3 的错误日志：
`copying /home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/Tools/scripts/pydoc3 -> build/scripts-3.9
copying /home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/Tools/scripts/idle3 -> build/scripts-3.9
copying /home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/Tools/scripts/2to3 -> build/scripts-3.9
renaming build/scripts-3.9/pydoc3 to build/scripts-3.9/pydoc3.9
renaming build/scripts-3.9/idle3 to build/scripts-3.9/idle3.9
renaming build/scripts-3.9/2to3 to build/scripts-3.9/2to3-3.9
x86_64-openwrt-linux-musl-gcc -L/home/oldchen/build/openwrt-21.02/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/oldchen/build/openwrt-21.02/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro -L/home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12 -L/home/oldchen/build/openwrt-21.02/staging_dir/target-x86_64_musl/usr/lib -L/home/oldchen/build/openwrt-21.02/staging_dir/target-x86_64_musl/lib -L/home/oldchen/build/openwrt-21.02/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/home/oldchen/build/openwrt-21.02/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro -L/home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12 -L/home/oldchen/build/openwrt-21.02/staging_dir/target-x86_64_musl/usr/lib -L/home/oldchen/build/openwrt-21.02/staging_dir/target-x86_64_musl/lib -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -g  -Xlinker -export-dynamic -o Programs/_testembed Programs/_testembed.o -L. -lpython3.9 -ldl  -lpthread -lm -lz   -lm
sed -e "s,@EXENAME@,/usr/bin/python3.9," < ./Misc/python-config.in >python-config.py
LC_ALL=C sed -e 's,\$(\([A-Za-z0-9_]*\)),\$\{\1\},g' < Misc/python-config.sh >python-config
make[5]: Leaving directory '/home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12'
make[4]: Leaving directory '/home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12'
# Use host pip to install python-setuptools
/home/oldchen/build/openwrt-21.02/staging_dir/hostpkg/bin/pip3.9 --disable-pip-version-check --cache-dir "/home/oldchen/build/openwrt-21.02/dl/pip-cache" install --ignore-installed --root=/home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/install-setuptools --prefix=/usr /home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/Lib/ensurepip/_bundled/setuptools-58.1.0-py3-none-any.whl
bash: line 1: /home/oldchen/build/openwrt-21.02/staging_dir/hostpkg/bin/pip3.9: No such file or directory
make[3]: *** [Makefile:379: /home/oldchen/build/openwrt-21.02/build_dir/target-x86_64_musl/Python-3.9.12/.built] Error 127
make[3]: Leaving directory '/home/oldchen/build/openwrt-21.02/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/compile#71.21#8.79#88.80
    ERROR: package/feeds/packages/python3 failed to build.
make[2]: *** [package/Makefile:116: package/feeds/packages/python3/compile] Error 1
make[2]: Leaving directory '/home/oldchen/build/openwrt-21.02'
make[1]: *** [package/Makefile:110: /home/oldchen/build/openwrt-21.02/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/oldchen/build/openwrt-21.02'
make: *** [/home/oldchen/build/openwrt-21.02/include/toplevel.mk:230: world] Error 2
`

ruby 的错误日志：
![2022-05-05 142408](https://user-images.githubusercontent.com/14952222/166886015-5759acc8-56f3-4fe0-ae6d-35ceeb5a6766.jpg)

**Comment by 1715173329** [comment]
依赖装全了吗？

**Comment by imoldchen** [comment]
> 依赖装全了吗？

依赖应该是没有遗漏的

`sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python3-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev`

<img width="411" alt="image" src="https://user-images.githubusercontent.com/14952222/166887998-64ff0905-dc78-43d7-804f-8e7abe8e6bcf.png">

**Comment by 1715173329** [comment]
host 或 buildroot 环境有问题。
建议通过 opde container 进行编译，具体参见 readme。
