### ISSUE TITLE
方便21.02的softethervpn更新下最新rtm么

### ISSUE THREAD

**Issue by SakuraFallingMad** [immortalwrt/packages#398]
偶然情况下，softethervpn突然弹出升级服务端版本才发现，21.02的编译出来的版本不是最新rtm的。如图：
![image](https://user-images.githubusercontent.com/31793080/175300485-5497980a-1323-4613-85ef-5bad13196141.png)
master branch的是最新的。方便处理一下么，比较喜欢求稳

**Comment by 1715173329** [comment]
“最新版本”“求稳”

**Comment by SakuraFallingMad** [comment]
稳定版中的追新求稳貌似挺正常，啊嘿~
