### ISSUE TITLE
大佬您好，oscam编译错误了

### ISSUE THREAD

**Issue by 281677160** [immortalwrt/packages#494]
21.02跟18.06分支的oscam都编译错误了，其他分支的不知道是不是会错误，麻烦大佬看看能修复不

![QQ截图20221023101725](https://user-images.githubusercontent.com/66651997/197370116-14dc5701-3f14-44df-8374-3c276c33b1f1.png)

[详细日志.txt](https://github.com/immortalwrt/immortalwrt/files/9845610/default.txt)

**Comment by 1715173329** [comment]
Our CI reports it builds. Please check your environment.
https://github.com/immortalwrt/packages/actions/runs/3326626099

**Comment by 281677160** [comment]
> Our CI reports it builds. Please check your environment. https://github.com/immortalwrt/packages/actions/runs/3326626099

感谢回复，我再编译试试看，我用的云编译，ubuntu22.04的，依赖安装是用的 sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

我昨晚上编译还错误的
![QQ截图20221026144151](https://user-images.githubusercontent.com/66651997/197953801-dcf84c1b-c01b-4244-a7a1-8350bdf42a88.png)
