### ISSUE TITLE
最新编译的固件版本softethervpn和openconnectvpn无法正常连接

### ISSUE THREAD

**Issue by myfalcom** [immortalwrt/packages#519]
最新编译的固件版本softethervpn和openconnectvpn无法正常连接.
提示连接后立即断线，重试后依旧。

**Comment by myfalcom** [comment]
看了其他帖子，应该是softethervpn 5.02版本断线情况严重，并且配置openvpn时不显示配置的端口。
退回到5.01版本时正常。

**Comment by myfalcom** [comment]
最新更新下，R4S无法保存softethervpn 配置;
使用的是luci-app-softethervpn5软件，配置好后，重启路由器，配置恢复为初始化配置；
查看server配置信息为初始化配置，但手动关闭服务，重新刷入配置后开启服务，即可正常。

**Comment by 1715173329** [comment]
什么叫做无法保存？
