### ISSUE TITLE
qBittorrent-Enhanced-Edition编译错误

### ISSUE THREAD

**Issue by eggydutch** [immortalwrt/packages#52]
openwrt-21.02分支下，qBittorrent-Enhanced-Edition编译错误（编译固件为R2S）。
![FireShot Capture 050](https://user-images.githubusercontent.com/59375032/108621344-2a9b2500-746d-11eb-9d0c-0dbf18d135ef.png)

**Comment by 1715173329** [comment]
Fixed in 806ed5325c166b.
