### ISSUE TITLE
新增加packages/devel/gn/Makefile编译错误

### ISSUE THREAD

**Issue by swxk521** [immortalwrt/packages#522]
x86 18.06-k5.4  用的[Actions-OpenWrt]在线编译错
新更改的naiveproxy这个gn/host错误。去掉naiveproxy正常
    ERROR: package/feeds/packages/gn [host] failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1
make[2]: Entering directory '/workdir/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[3]: Entering directory '/workdir/openwrt/feeds/packages/devel/gn'
MAKEFLAGS="" /workdir/openwrt/staging_dir/host/bin/ninja  -j1 -C /workdir/openwrt/build_dir/hostpkg/gn-2022-11-10-1c4151ff/out
ninja: Entering directory `/workdir/openwrt/build_dir/hostpkg/gn-2022-11-10-1c4151ff/out'
[1/91] LINK gn
FAILED: gn 
clang++ -O3 -fdata-sections -ffunction-sections -Wl,--gc-sections -flto -fwhole-program-vtables -Wl,--as-needed -pthread -o gn -Wl,--start-group src/gn/gn_main.o base.a gn_lib.a -Wl,--end-group -ldl
/usr/bin/ld: base.a: error adding symbols: archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/devel/gn'
time: package/feeds/packages/gn/host-compile#0.19#0.07#0.24
make[3]: *** [Makefile:57: /workdir/openwrt/build_dir/hostpkg/gn-2022-11-10-1c4151ff/.built] Error 1
    ERROR: package/feeds/packages/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/packages/gn/host/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by 1715173329** [comment]
Any logs? Please make sure you have installed all of the required dependencies that I mentioned in README.
