### ISSUE TITLE
使用master源码无法使用socat

### ISSUE THREAD

**Issue by Potterli20** [immortalwrt/packages#530]
使用master源码无法使用socat，看上去端口没有开到

**Comment by Potterli20** [comment]
测试一下，就内网正常，外网无法正在，端口没有开

**Comment by Potterli20** [comment]
@1715173329 http://www.dest-unreach.org/socat/download/ 有更新，最新1.7.4.4

**Comment by 1715173329** [comment]
防火墙看了吗？

**Comment by ksong008** [comment]
@1715173329 socat restart下看看呗

**Comment by Potterli20** [comment]
> 防火墙看了吗？

防火墙看了![Screenshot_2022-11-20-02-20-51-847_com.termux.jpg](https://user-images.githubusercontent.com/28734349/202878595-faa6a174-ec4f-49ba-8879-f693c57cfc1a.jpg)

**Comment by Potterli20** [comment]
> 防火墙看了吗？

真会笑了，防火墙那边全乱了
如:我在防火墙开了ftp端口不生效，在socat开端口生效了哦。我单在socat就不生效哦

**Comment by Potterli20** [comment]
> @1715173329 socat restart下看看呗

reatart无效，重启也无效

**Comment by 1715173329** [comment]
不会用 nftables 就不要用了，换 21.02 分支。

**Comment by Potterli20** [comment]
> 不会用 nftables 就不要用了，换 21.02 分支。

我是用r68s的，并非x86，我看了一下依赖 我没有选中nftable，而且路由上也没有nftables命令。
这个是我使用的config，没有加其他，默认的https://github.com/Potterli20/file/blob/main/file/r68s/immortalwrt/config

**Comment by 1715173329** [comment]
那你挺厉害的，选 fw3 还勾 nftables 和 iptables-nft。配置删了重新选吧。

**Comment by Potterli20** [comment]
> 那你挺厉害的，选 fw3 还勾 nftables 和 iptables-nft。配置删了重新选吧。

okkk

**Comment by Potterli20** [comment]
> 那你挺厉害的，选 fw3 还勾 nftables 和 iptables-nft。配置删了重新选吧。

删了重新选择一样，我感觉默认开启nf的

**Comment by Potterli20** [comment]
> > 那你挺厉害的，选 fw3 还勾 nftables 和 iptables-nft。配置删了重新选吧。
> 
> 删了重新选择一样，我感觉默认开启nf的

我已经编译了四次，做了四次也是一样的问题
