### ISSUE TITLE
adguardhome [openwrt-21.02] 程序启动失败

### ISSUE THREAD

**Issue by victordou** [immortalwrt/packages#544]
固件自己编译的
和从 [immortal](https://downloads.immortalwrt.org/releases/21.02.3/targets/x86/64/immortalwrt-21.02.3-x86-64-generic-squashfs-combined-efi.vmdk) 下载的，现象一样。
1. /etc/init.d/adguardhome status = inactive
2. 3000端口没有bind, 程序没动静。
3. 手动运行 /usr/bin/AdGuardHome -c /etc/adguardhome.yaml -w /var/adguardhome --no-check-update 
可以启动

**Comment by 1715173329** [comment]
/etc/config/adguardhome
enabled 1
