### ISSUE TITLE
尝试更新 qBittorrent 至 4.5.0 失败。

### ISSUE THREAD

**Issue by zdz2019** [immortalwrt/packages#568]
[1/231] Automatic MOC for target qbt_base
AutoMoc: /home/zdz2019/immortalwrt/build_dir/target-mipsel_24kc_musl/qBittorrent-release-4.5.0/src/base/interfaces/iapplication.h:0:1: note: No relevant classes found. No output generated.
[231/231] Linking CXX executable qbittorrent-nox
FAILED: qbittorrent-nox

看起来像是新版本增加了一个什么模块，不知道应该怎么配置参数。

**Comment by 1715173329** [comment]
是最后链接失败了，可能与你的 host 环境有关。

**Comment by 1715173329** [comment]
21.02 看起来确实是烂了

**Comment by 1715173329** [comment]
好了。
