### ISSUE TITLE
MT7621 无法正常使用 qbittorrent。

### ISSUE THREAD

**Issue by zdz2019** [immortalwrt/packages#573]
为一台 MT7621 芯片的路由编译成功，也能正常运行，系统日志无报错，但实际无法打开 web 控制台，无法使用。
但在另一台路由器，WRT32x 则完全正常。

是否因为 QT 平台不支持 mipsel 芯片了？或者是需要打个补丁？

**Comment by 1715173329** [comment]
PR is welcome.

**Comment by woohowe** [comment]
我与昨天下载zbt-we1326最新的21.02.4的包，通过Uboot写入后，无法进luci后台管理，网络地址获取为169段的无效地址。

**Comment by 1715173329** [comment]
TTL 日志。
你的问题与此 issue 无关，请去主库开新的 issue。

**Comment by woohowe** [comment]
这是来自QQ邮箱的自动回复邮件。
 
你好，邮件已收到，尽快给你回复。

**Comment by Beaverfffan** [comment]
Yes,qbittorrent enhanced edition with qt6 doesn't suppurt mips.U need  to trans to qbittorrent-simple or older qt5 based qb.

**Comment by woohowe** [comment]
这是来自QQ邮箱的自动回复邮件。
 
你好，邮件已收到，尽快给你回复。

**Comment by woohowe** [comment]
这是来自QQ邮箱的自动回复邮件。
 
你好，邮件已收到，尽快给你回复。
