### ISSUE TITLE
net/cloudflared(FTBFS): force bump quic-go on go1.20

### ISSUE THREAD

**Issue by mochaaP** [immortalwrt/packages#698]
<https://github.com/immortalwrt/packages/actions/runs/4725339224/jobs/8383627775#step:5:4318> due to a outdated dependency (maybe plus some incorrect module `replace`s), the package could not build with go1.20 on the master branch.

## Solution

a). Patch `go.mod` ourselves for now
b). Ask upstream about bumping deps

**Comment by 1715173329** [comment]
> b). Ask upstream about bumping deps

Unfortunately we got no response from upstream.
See https://github.com/cloudflare/cloudflared/issues/888

**Comment by mochaaP** [comment]
Bumping deps and testing on my local machine. Will submit a pull request to upstream if it works.

**Comment by mochaaP** [comment]
PR is live at <https://github.com/cloudflare/cloudflared/pull/945>. reviews are welcomed.

**Comment by 1715173329** [comment]
it somehow compiles again in 2023.5.1.

**Comment by stefanb** [comment]
"somehow" -> due to https://github.com/cloudflare/cloudflared/commit/9426b603082905d0af8a07bdac866bc1d9c37cba
