### ISSUE TITLE
uugamebooster 上游的 uu.tar.gz x86_64 平台版本号与其他平台版本不同如何处理？

### ISSUE THREAD

**Issue by Sunshine-Planet** [immortalwrt/packages#703]
v3.9.2 版本更新后，目前网易上游 x86_64 平台版本为 v3.12.4 ，其他平台为 v3.11.2

试编辑 net/uugamebooster/makefile 使用以下逻辑不同平台编译通过，在现在不同平台版本号不统一的情况下，是否有更好的处理方法？

```
PKG_VERSION:=v3.11.2
ifeq ($(ARCH),x86_64)
	PKG_VERSION:=v3.12.4
endif
```

**Comment by 1715173329** [comment]
No idea，我只想给网易一声亲切的问候

**Comment by Sunshine-Planet** [comment]
我注意到写这个插件的人有想做一个安装好之后能在本地自动更新的功能，但好像没写完。

我的理解是，插件更新的逻辑是把 uu.tar.gz 解压至 /usr/share/uugamebooster 下

做成一个使用类似 `uugamebooster update` 命令就能更新的形式，这也方便使用。天灵兄认为这样可行吗？

**Comment by 1715173329** [comment]
没什么必要

**Comment by 1715173329** [comment]
姑且先更新到了 3.11.2 3516283830deb9fbb32d7c2981debcc972f3d433
