### ISSUE TITLE
libpcre

### ISSUE THREAD

**Issue by Aukansh** [immortalwrt/packages#746]
WARNING: Makefile 'package/feeds/packages/slang2/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/snort/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/snort3/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/syslog-ng/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/tvheadend/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/uwsgi/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/wget/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/wget/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zabbix/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/packages/zsh/Makefile' has a dependency on 'libpcre', which does not exist

**Comment by 1715173329** [comment]
Your tree is out-of-date, run make dirclean and reinstall feeds
