### ISSUE TITLE
2305 分支的 ddns-go 存在时区问题

### ISSUE THREAD

**Issue by zzcabc** [immortalwrt/packages#754]
尝试各种设置时区的方式，使用luci-app-ddns-go控制启动ddns-go，时间均为UTC时区，导致无法正常通过网页获取ip及更新域名ip

尝试方法 安装 `zoneinfo-asia` 更改 `/etc/config/system` 为 `Asia/Shanghai`
`ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`
在init.d 中 使用 `procd_set_param env TZ="Asia/Shanghai"`
均无法正常获取时区

使用命令行 启动ddns-go 是正常的，在2102版本中，使用luci-app-ddns-go 也是正常的，

**Comment by douglarek** [comment]
> 尝试各种设置时区的方式

luci 页面上不是有设置时区吗，那个显示为 什么？那个之前确实是默认 UTC，最近的版本似乎会根据你本地默认为 `Asia/Shanghai` 不用修改任何东西。

**Comment by zzcabc** [comment]
> > 尝试各种设置时区的方式
> 
> luci 页面上不是有设置时区吗，那个显示为 什么？那个之前确实是默认 UTC，最近的版本似乎会根据你本地默认为 `Asia/Shanghai` 不用修改任何东西。

在系统-系统-常规设置-时区，已经选择了Asia/Shanghai，也曾经设置过 Asia/Singapore，Asia/HongKong，几个欧洲时区都设置过，依旧默认UTC时区，固件是昨天编译的固件 https://github.com/zzcabc/OpenWrt_Action/actions/runs/5190981849 在此之前已经在ddns-go的issue中提过，正因为在命令行启动时区是正确的，所以我才到这里提的issue，因为我没找到immoralwrt的luci-app-ddns-go源项目是哪里的

**Comment by 1715173329** [comment]
修改 `/etc/init.d/ddns-go`
在 `procd_add_jail_mount_rw` 下面加上：
`procd_add_jail_mount "/etc/TZ"`
`procd_add_jail_mount "/etc/ssl/"`

然后重启服务看看

**Comment by zzcabc** [comment]
> 修改 `/etc/init.d/ddns-go` 在 `procd_add_jail_mount_rw` 下面加上： `procd_add_jail_mount "/etc/TZ"` `procd_add_jail_mount "/etc/ssl/"`
> 
> 然后重启服务看看

`procd_add_jail_mount "/etc/TZ`       似乎并没有TZ文件，改成 `procd_add_jail_mount "/etc/localtime"` 测试有效

**Comment by xiaohao5812** [comment]
> 修改 在 下面加上：`/etc/init.d/ddns-go``procd_add_jail_mount_rw` `procd_add_jail_mount "/etc/TZ"` `procd_add_jail_mount "/etc/ssl/"`
> 
> 然后重启服务看看

这个问题现在依然没有修复，我的ImmortalWrt 23.05.3 ，内核版本 | 5.15.162，，，，，，

ddns-go版本，6.7.0，，

时区依然是错误的相差8小时
