### ISSUE TITLE
sing-box 编译失败

### ISSUE THREAD

**Issue by mitsukileung** [immortalwrt/packages#782]
make[3]: Entering directory '/home/koysuke/openwrt2305/feeds/packages/net/sing-box'
mkdir -p /home/koysuke/openwrt2305/dl
SHELL= flock /home/koysuke/openwrt2305/tmp/.sing-box-1.3.0.tar.gz.flock -c '  	/home/koysuke/openwrt2305/scripts/download.pl "/home/koysuke/openwrt2305/dl" "sing-box-1.3.0.tar.gz" "e89ffdadf11d4b34d12b2c0659efea0f0786b2396ea4638c61a06e7772783ca5" "" "https://codeload.github.com/SagerNet/sing-box/tar.gz/v1.3.0?"    '
Hash of the local file sing-box-1.3.0.tar.gz does not match (file: 19b83d9cbd4e241da2ec9cb14110826b2694590950356a4f4051081ec4b4c92d, requested: e89ffdadf11d4b34d12b2c0659efea0f0786b2396ea4638c61a06e7772783ca5) - deleting download.
make[3]: *** [Makefile:151: /home/koysuke/openwrt2305/dl/sing-box-1.3.0.tar.gz] Error 2
make[3]: Leaving directory '/home/koysuke/openwrt2305/feeds/packages/net/sing-box'
time: package/feeds/packages/sing-box/compile#0.12#0.07#0.17
    ERROR: package/feeds/packages/sing-box failed to build.
make[2]: *** [package/Makefile:120: package/feeds/packages/sing-box/compile] Error 1
make[2]: Leaving directory '/home/koysuke/openwrt2305'
make[1]: *** [package/Makefile:114: /home/koysuke/openwrt2305/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/koysuke/openwrt2305'
make: *** [/home/koysuke/openwrt2305/include/toplevel.mk:232：world] 错误 2

**Comment by 1715173329** [comment]
你本地文件没更新。重新编译即可

**Comment by mitsukileung** [comment]
> 你本地文件没更新。重新编译即可

本地文件要怎样更新？
make clean 之后 还是不行

**Comment by 1715173329** [comment]
删除 dl
