### ISSUE TITLE
天灵大佬，我注意到你提交了 xray-core 1.8.4, 但似乎很久没有更新在openwrt packages 中

### ISSUE THREAD

**Issue by yukeiyang** [immortalwrt/packages#896]
@1715173329 是因为 [#842](https://github.com/immortalwrt/packages/issues/842) "xray-core不支持使用go 1.21编译" 导致的问题么？
大概何时才会放出？等了 10 多天了。哈哈。感谢你的工作。

**Comment by 1715173329** [comment]
https://github.com/openwrt/packages/commit/19a2d9abd081aec75fcbf71785100cf6e04fc13a

**Comment by yukeiyang** [comment]
感谢。

**Comment by yukeiyang** [comment]
以 x86 为例，openwrt 官网列出的 [xray-core 的 ipk](https://downloads.openwrt.org/releases/packages-22.03/x86_64/packages/) 仍然停留在 1.8.3-1, 我需要自己另行编译出 1.8.4 么? 感谢。

**Comment by 1715173329** [comment]
升级 23.05 即可

**Comment by yukeiyang** [comment]
thank you.

**Comment by barton0426** [comment]
避免开新issue了，想问大佬一下，为什么https://downloads.immortalwrt.org/releases/里面的xray都还是1.8.3版本

**Comment by yukeiyang** [comment]
如大佬所说，你升级到 23.05 就好了。
