### ISSUE TITLE
请问 cloudflared 包为什么消失了？

### ISSUE THREAD

**Issue by Mosney** [immortalwrt/packages#925]
是过时不再需要还是什么别的原因呢？

**Comment by 1715173329** [comment]
联系 cf 修复 go 1.21 编译即可。

**Comment by Mosney** [comment]
> 联系 cf 修复 go 1.21 编译即可。

我觉得新版本出现问题至少可以保留一下旧版本🤔

**Comment by cherinyy** [comment]
https://github.com/cloudflare/cloudflared/issues/1054
