### ISSUE TITLE
移除V2rayA的xray-core依赖

### ISSUE THREAD

**Issue by Gaojianli** [immortalwrt/packages#940]
`xray-core`和`v2ray-core`在功能上目前并不能做到互相替换，尤其是前者并不支持多节点的情况下。

目前，上游提供的Openwrt包中已经移除了`xray-core`作为依赖：https://github.com/v2rayA/v2raya-openwrt/blob/master/v2raya/Makefile

不知immortalwrt中提供的`v2rayA`能否考虑移除这一依赖以给用户提供更多的选择（以及节约空间）：https://github.com/immortalwrt/packages/blob/master/net/v2raya/Makefile#L43

**Comment by 1715173329** [comment]
然而后者的 udp 支持依然是一团糟。

openwrt 的软件包架构无法处理复杂的依赖，因此默认选择 Xray。你可以指定忽略软件包原本的依赖并自行安装。

https://github.com/openwrt/packages/issues/21450#issuecomment-1609789429
