### ISSUE TITLE
zerotier 打包缺失服务项文件 /etc/init.d/zerotier

### ISSUE THREAD

**Issue by CrazyBoyFeng** [immortalwrt/packages#963]
代码里有 [net/zerotier/files/etc/init.d/zerotier](https://github.com/immortalwrt/packages/blob/4b932defdc87de4639cf7cd3b1630ff81f0b2246/net/zerotier/files/etc/init.d/zerotier) 这个文件，但是不知道为什么 ImmortalWrt 官网的 ipk 包就没有这个文件。  

这个文件是启动项/服务项配置文件，缺失了这个文件，`zerotier` 就不会自动启动、热更新配置了，需要手动启动或写入启动脚本。

我分别下载了 OpenWrt 官网 21.02 的 [zerotier_1.10.2-1_x86_64.ipk](https://downloads.openwrt.org/releases/packages-21.02/x86_64/packages/zerotier_1.10.2-1_x86_64.ipk) 和 [zerotier_1.10.2-1_mipsel_24kc.ipk](https://downloads.openwrt.org/releases/packages-21.02/mipsel_24kc/packages/zerotier_1.10.2-1_mipsel_24kc.ipk) 以及 23.05 的 [zerotier_1.12.2-2_x86_64.ipk](https://downloads.openwrt.org/releases/packages-23.05/x86_64/packages/zerotier_1.12.2-2_x86_64.ipk) 和 [zerotier_1.12.2-2_mipsel_24kc.ipk](https://downloads.openwrt.org/releases/packages-23.05/x86_64/packages/zerotier_1.12.2-2_mipsel_24kc.ipk)，将其解包，都能够找到 `./data.tar.gz/./etc/init.d/zerotier`，说明这个文件不存在平台差异或版本差异。  
但 ImmortalWrt 官网上 21.02 的 [zerotier_1.12.2-1_x86_64.ipk](https://downloads.immortalwrt.org/releases/packages-21.02/x86_64/packages/zerotier_1.12.2-1_x86_64.ipk) 和 [zerotier_1.12.2-1_mipsel_24kc.ipk](https://downloads.immortalwrt.org/releases/packages-21.02/mipsel_24kc/packages/zerotier_1.12.2-1_mipsel_24kc.ipk) 以及 23.05 的 [zerotier_1.12.2-2_x86_64.ipk](https://downloads.immortalwrt.org/releases/packages-23.05/x86_64/packages/zerotier_1.12.2-2_x86_64.ipk) 和 [zerotier_1.12.2-2_mipsel_24kc.ipk](https://downloads.immortalwrt.org/releases/packages-23.05/x86_64/packages/zerotier_1.12.2-2_mipsel_24kc.ipk) 下载后解包都没有 `./data.tar.gz/./etc/init.d/zerotier`。  
我没有编译条件，所以看不出来问题在什么地方。

**Comment by 1715173329** [comment]
luci-app-zerotier
