### ISSUE TITLE
发现个依赖缺失

### ISSUE THREAD

**Issue by VIKINGYFY** [immortalwrt/packages#992]
WARNING: Makefile 'package/feeds/luci/luci-proto-cni/Makefile' has a dependency on 'cni-protocol', which does not exist

用的云编译，编译时拉取的这个[提交](https://github.com/immortalwrt/immortalwrt/commit/0b13de911608f96596ffe36c1410b10f9092c73a)

**Comment by zxlhhyccc** [comment]
上游已更新，等天灵合并。。。
